#see for java tunning https://docs.oracle.com/cd/E15523_01/web.1111/e13814/jvm_tuning.htm#PERFM161
version: '3.8'
services:

 ##########################################################################     
 # database service
 ##########################################################################       
  postgres_db:
    container_name: postgres
    image: postgres:latest
    ports:
        - 5432:5432
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: qwerty
        POSTGRES_DB: postgres  


 ##########################################################################     
 # eureka
 ##########################################################################  
  eureka_server:
    container_name: eureka-server
    image: calculator/microservice-docker-eureka-server:0.0.1-SNAPSHOT
    environment:
       - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
    ports:
      - 8761:8761 

 ##########################################################################     
 # apigateway
 ##########################################################################  
  apigateway:
    container_name: apigateway
    image: calculator/microservice-docker-apigateway:0.0.1-SNAPSHOT
    environment:
       - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
    ports:
      - 8080:8080 
    depends_on:
      - eureka_server
      
##########################################################################     
 # admin-server
 ##########################################################################  
  admin_server:
    container_name: admin-server
    image: calculator/microservice-docker-admin-server:0.0.1-SNAPSHOT
    environment:
       - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
    ports:
      - 8081:8081 
    depends_on:
      - eureka_server

 ##########################################################################     
 #product service
 ##########################################################################  
  calculator_provider:
    container_name: calculator-provider
    image: calculator/microservice-docker-calculator-provider:0.0.1-SNAPSHOT
    environment:
       - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
    ports:
      - 8082:8082
    depends_on:
      - eureka_server
      - apigateway 
      
 ##########################################################################     
 #customer service
 ##########################################################################        
  calculator_service:
    #container_name: calculator-service
    image: calculator/microservice-docker-calculator-service:0.0.1-SNAPSHOT   
    environment:
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/    
    ports:
      - "8083:8083"                
    depends_on:
      - eureka_server
      - apigateway
      - postgres_db
      - calculator_provider