#see for java tunning https://docs.oracle.com/cd/E15523_01/web.1111/e13814/jvm_tuning.htm#PERFM161
version: '3.8'
services:

 ##########################################################################     
 # database service
 ##########################################################################       
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    ports:
        - 5432:5432
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: qwerty
        POSTGRES_DB: calculator

 ##########################################################################     
 # eureka
 ##########################################################################  
  eureka_server:
    container_name: eureka-server
    image: adelgrosso1978/calculator-eureka-server:latest
    environment:
       - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
    ports:
      - 8761:8761 

 ##########################################################################     
 # apigateway
 ##########################################################################  
  apigateway:
    container_name: apigateway
    #image: calculator/apigateway:0.0.1
    image: adelgrosso1978/calculator-api-gateway:latest
    environment:
       - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://eureka-server:8761/eureka/
    ports:
      - 8080:8080 
    depends_on:
      - eureka_server
      
 ##########################################################################     
 # provider
 ##########################################################################  
  calculator_provider:
    container_name: calculator-provider
    image: adelgrosso1978/calculator-provider:latest
    environment:
       - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://eureka-server:8761/eureka/
    ports:
      - 8082:8082
    depends_on:
      - eureka_server
      - apigateway 
      
 ##########################################################################     
 #service
 ##########################################################################        
  calculator_service:
    container_name: calculator-service
    image: adelgrosso1978/calculator-service:latest   
    environment:
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://eureka-server:8761/eureka/
         -DSPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/calculator
         -DSPRING_DATASOURCE_USERNAME=postgres
         -DSPRING_DATASOURCE_PASSWORD=qwerty
         -DSPRING_JPA_HIBERNATE_DDL_AUTO=create
    ports:
      - "8083:8083"                
    depends_on:
      - postgres_db
      - eureka_server
      - apigateway
      - calculator_provider