## YAML Template.
---
server:
    port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
      - id: calculator-service
        uri: lb://calculator-service
        predicates:
        - Path=/calculator/**